{
    "name": "Construction Field Operations",
    "summary": "Daily Site Logs with labour, quantities, photos, signature and supervisor review",
    "version": "19.0.0.9.1",
    "author": "Construction Suite",
    "license": "OPL-1",
    "category": "Construction",
    "depends": ["cs_core", "cs_hse"],
    "data": [
        "security/ir.model.access.csv",
        "security/cs_field_rules.xml",
        "security/cs_site_record_rules.xml",
        "views/cs_field_views.xml",
        "views/project_link_views.xml",
        "views/cs_site_record_views.xml",
        "views/cs_field_issue_views.xml",
        "views/cs_phase4_views.xml",
        "views/cs_site_instruction_views.xml",
        "report/cs_field_reports.xml",
        "report/cs_si_report.xml",
        "report/cs_minutes_report.xml",
    ],
    "installable": True,
    "application": False,
}
