{
    "name": "Construction Controls",
    "summary": "RFIs, Change Orders and Submittals as dedicated business records",
    "version": "19.0.0.7.0",
    "author": "Construction Suite",
    "license": "OPL-1",
    "category": "Construction",
    "depends": ["cs_core", "sale", "account"],
    "data": [
        "security/ir.model.access.csv",
        "security/cs_rules.xml",
        "data/cron.xml",
        "views/cs_rfi_views.xml",
        "views/cs_change_order_views.xml",
        "views/cs_submittal_views.xml",
        "views/cs_menus.xml",
        "views/cs_overview_views.xml",
        "views/project_link_views.xml",
        "report/cs_report_actions.xml",
        "report/cs_report_templates.xml",
    ],
    "installable": True,
    "application": True,
}
