from . import oqb_instance
from . import oqb_logger
from . import oqb_mapper
from . import oqb_utils
from . import oqb_res_partner
from . import oqb_account
from . import oqb_product_template
from . import oqb_sale_order
from . import oqb_hr_employee
from . import oqb_purchase_order
from . import oqb_payment
