{
    "name": "GTE Construction Controls",
    "summary": "RFIs, Change Orders and Submittals as dedicated business records",
    "version": "19.0.0.5.0",
    "author": "Green Tech Electric",
    "license": "OPL-1",
    "category": "Construction",
    "depends": ["gte_core", "sale", "account"],
    "data": [
        "security/ir.model.access.csv",
        "security/gte_rules.xml",
        "data/cron.xml",
        "views/gte_rfi_views.xml",
        "views/gte_change_order_views.xml",
        "views/gte_submittal_views.xml",
        "views/gte_menus.xml",
        "views/gte_overview_views.xml",
        "views/project_link_views.xml",
        "report/gte_report_actions.xml",
        "report/gte_report_templates.xml",
    ],
    "installable": True,
    "application": True,
}
