# -*- encoding: utf-8 -*-
"""Kiosk shell controllers for the EH attendance suite.

This module owns the device pairing and heartbeat surface. It does not
own the actual capture / match UI - that lives in the matching modality
module (eh_hr_face_kiosk for face, future eh_hr_fp_kiosk for
fingerprint, etc.) so multiple capture types can share one device
registry, one site model, and one audit trail.

Authentication model
--------------------

* Pairing endpoint uses a one-time pairing code that an admin generates
  in Odoo and reads aloud (or scans as QR) on the kiosk during setup.
  The code is short-lived and single-use. The server, on success,
  issues a long opaque device_token.
* Every other endpoint requires the device_token in the X-EH-Kiosk-Token
  header. A revoked or unknown token returns 401.
* Endpoints are rate-limited per IP via Odoo's standard `routes` rate
  limit when present; otherwise we apply a soft per-token cap by
  recording last_seen and rejecting bursts shorter than 1 second.
"""
import json
import logging
import time

from odoo import _, http
from odoo.exceptions import AccessError
from odoo.http import request

_logger = logging.getLogger(__name__)


# In-memory pairing PIN cache. PINs are short-lived (5 min) and stored
# in this process only - acceptable because pairing is a manual step
# that an admin and the kiosk operator perform together. For
# multi-worker deployments the admin retries on the worker that holds
# the PIN, or the eh_hr_face_kiosk module can later promote this to
# ir.config_parameter.
_PAIRING_PINS = {}
_PAIRING_TTL_SECONDS = 300
_MIN_HEARTBEAT_INTERVAL = 1.0


def _now():
    return time.time()


def _expire_pairing_pins():
    cutoff = _now() - _PAIRING_TTL_SECONDS
    stale = [pin for pin, info in _PAIRING_PINS.items() if info['issued_at'] < cutoff]
    for pin in stale:
        _PAIRING_PINS.pop(pin, None)


def _get_device_by_token(token):
    if not token:
        return None
    Device = request.env['eh.hr.kiosk.terminal'].sudo()
    return Device.search([
        ('device_token', '=', token),
        ('active', '=', True),
    ], limit=1)


def _client_ip():
    return request.httprequest.headers.get('X-Real-IP') \
        or request.httprequest.headers.get('X-Forwarded-For', '').split(',')[0].strip() \
        or request.httprequest.remote_addr


def _client_user_agent():
    return request.httprequest.headers.get('User-Agent', '')[:255]


def _json_response(payload, status=200):
    return request.make_response(
        json.dumps(payload),
        headers=[('Content-Type', 'application/json')],
        status=status,
    )


class EhHrKioskController(http.Controller):

    @http.route('/eh_hr/kiosk/pair', type='http', auth='public', methods=['POST'], csrf=False)
    def pair(self, **kwargs):
        """Trade a one-time pairing PIN for a long-lived device token.

        Body (JSON or form): site_code, pin, device_name (optional).
        Response 200: {device_token, site_id, site_name}.
        Response 4xx: {error}.

        The PIN is generated by an admin in Odoo via the kiosk site
        action. It is one-shot and expires after PAIRING_TTL_SECONDS.
        """
        _expire_pairing_pins()
        try:
            data = json.loads(request.httprequest.data) if request.httprequest.data else {}
        except ValueError:
            data = {}
        data = {**kwargs, **data}

        site_code = (data.get('site_code') or '').strip()
        pin = (data.get('pin') or '').strip()
        device_name = (data.get('device_name') or '').strip() or _('Unnamed kiosk')

        if not site_code or not pin:
            return _json_response({'error': 'site_code and pin are required'}, status=400)

        info = _PAIRING_PINS.get(pin)
        if not info:
            return _json_response({'error': 'Invalid or expired pairing PIN'}, status=403)
        if info['site_code'] != site_code:
            return _json_response({'error': 'Pairing PIN does not match site code'}, status=403)
        if info['issued_at'] + _PAIRING_TTL_SECONDS < _now():
            _PAIRING_PINS.pop(pin, None)
            return _json_response({'error': 'Pairing PIN has expired'}, status=403)

        Site = request.env['eh.hr.kiosk.site'].sudo()
        site = Site.search([('code', '=', site_code), ('active', '=', True)], limit=1)
        if not site:
            return _json_response({'error': 'Unknown or inactive site'}, status=404)

        Device = request.env['eh.hr.kiosk.terminal'].sudo()
        device = Device.create({
            'name': device_name,
            'site_id': site.id,
            'last_ip': _client_ip(),
            'user_agent': _client_user_agent(),
        })

        _PAIRING_PINS.pop(pin, None)

        request.env['eh.hr.kiosk.event'].sudo().log(
            'device_register',
            device_id=device.id,
            ip_address=_client_ip(),
            user_agent=_client_user_agent(),
            notes='Device paired via /eh_hr/kiosk/pair',
            company_id=site.company_id.id,
        )

        return _json_response({
            'device_token': device.device_token,
            'site_id': site.id,
            'site_name': site.name,
            'site_code': site.code,
        })

    @http.route('/eh_hr/kiosk/heartbeat', type='http', auth='public', methods=['POST'], csrf=False)
    def heartbeat(self, **kwargs):
        """Record a kiosk heartbeat. Returns 200 OK with site config.

        Auth: X-EH-Kiosk-Token header.
        Body: ignored.
        """
        token = request.httprequest.headers.get('X-EH-Kiosk-Token')
        device = _get_device_by_token(token)
        if not device:
            return _json_response({'error': 'unauthorized'}, status=401)

        last_seen_ts = device.last_seen.timestamp() if device.last_seen else 0
        if last_seen_ts and _now() - last_seen_ts < _MIN_HEARTBEAT_INTERVAL:
            return _json_response({'error': 'rate limited'}, status=429)

        device._touch(ip_address=_client_ip(), user_agent=_client_user_agent())

        request.env['eh.hr.kiosk.event'].sudo().log(
            'device_heartbeat',
            device_id=device.id,
            ip_address=_client_ip(),
            company_id=device.company_id.id,
        )

        company = device.company_id
        return _json_response({
            'site_code': device.site_id.code,
            'site_name': device.site_id.name,
            'idle_seconds': company.eh_hr_kiosk_idle_seconds or 30,
            'match_threshold': company.eh_hr_match_threshold or 0.55,
            'geofence': {
                'enabled': bool(device.site_id.geofence_enabled),
                'lat': device.site_id.geofence_lat,
                'lng': device.site_id.geofence_lng,
                'radius_m': device.site_id.geofence_radius_m,
            },
        })

    @http.route('/eh_hr/kiosk/whoami', type='http', auth='public', methods=['GET'], csrf=False)
    def whoami(self, **kwargs):
        """Return device + site identity for the calling token. Used for
        kiosk shell bootstrap before the matching modality loads.
        """
        token = request.httprequest.headers.get('X-EH-Kiosk-Token')
        device = _get_device_by_token(token)
        if not device:
            return _json_response({'error': 'unauthorized'}, status=401)
        return _json_response({
            'device_id': device.id,
            'device_name': device.name,
            'site_code': device.site_id.code,
            'site_name': device.site_id.name,
            'company_id': device.company_id.id,
            'idle_seconds': device.company_id.eh_hr_kiosk_idle_seconds or 30,
        })


def issue_pairing_pin(site_code):
    """Server-side helper for the kiosk site form's "Pair a new device"
    button (added by the kiosk_site form action). Returns a freshly
    generated 6-digit PIN that is valid for PAIRING_TTL_SECONDS.

    Kept module-level so other EH HR modules can reuse the same in-memory
    pairing store rather than spinning up their own.
    """
    import secrets as _secrets
    _expire_pairing_pins()
    pin = ''.join(_secrets.choice('0123456789') for _ in range(6))
    _PAIRING_PINS[pin] = {
        'site_code': site_code,
        'issued_at': _now(),
    }
    return pin
